name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[observability]
enabled = true

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "anydrop.site"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "anydrop.site"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.anydrop.site", custom_domain = true },
  # { pattern = "quay.anydrop.site", custom_domain = true },
  # { pattern = "gcr.anydrop.site", custom_domain = true },
  # { pattern = "k8s-gcr.anydrop.site", custom_domain = true },
  # { pattern = "k8s.anydrop.site", custom_domain = true },
  # { pattern = "ghcr.anydrop.site", custom_domain = true },
  # { pattern = "cloudsmith.anydrop.site", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.anydrop.site", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
